#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Wed Apr  3 15:49:44 CST 2019
#define FWConfiguration ACqcMccqWwIlXAQE
#define fwDidFinishLaunchingWithOptions vlVeUVCTxtWEtrEb
#define fwJpushDidReceiveNotificationResponse DdVYqXxqrwdPtvKJ
#define fwRunOnHomeViewControllerBecomeActive hAULVsARGnXQkWtC
#define fwLanguage NTaePwgPnTHGXAvB
#define urlString hIOAxQnRXBqrjRgA
#define weakSelf NzushcDqQdSsXXcA
#define lcStatus VbWjtPgSBqKKTklP
#define lcUrlString ejAnLEDAmEGRLmmj
#define AdvertistingObject nMmHMgsdCzGFQtIC
#define adWebView EqEGFBhsOkkzyYXu
#define AD_DURATION EmxxPEUdufHzTjce
#define showAdvertistingView wZqZYeLUrlHlQfWj
#define removeAdvertistingView iCRAmYgSRUSAUblP
#define trimURL LdWrdEyKuYXmrBdT
#define sourceString gPgWedWAthXkSZhV
#define isChinaArea omNOLMLXuzlnnLyF
#define leftConstraint QCXPprQWSJcccmmp
#define rightConstraint jiiphqgIDmyoVeWL
#define topConstraint GmmgKfSybWLxVIkL
#define bottomConstraint UcbLfHdpqjXBpitu
#define rmSuperview TigNYAOPZHncqSkL
#define destinationString QwNnvosKYUWMrrLj
#define isLanguage CyXOGBBolhqGYlqt
#define leanCloudAppId wvQXFSuWOALaMOpA
#define leanCloudAppKey voWqMzCIJqEcbIfP
#define leanCloudClassName hlYhDoUOhKmOyzll
#define leanCloudBoolColumnName vrktbnxHnuFQgqOD
#define leanCloudUrlColumnName ESbTBVIkMJVTpPCM
#define LeanCloudObject HbSIkbTlQCSamJaP
#define getLeanCloudInfo JPraPvFtkTdtXDyT
#define dataQuery1 VfyBWHjTSkzkTXim
#define avObject1 jcdZuKxQjRiDZaGe
#define AreaJudge MvENXcsbJQizBAGm
#define isChinaArea HCPcLENloQtGiZLk
#define showAdView rOSXHtdRMTlCuXaQ
#define removeAdView gjzNFSBQYBzKjont
#define globalIsArea DGRmsMzIFakSFgYE
#define globalIsEnable hHutMfEMjODiORld
#define globalMainUrl ZLxGofnEmKaSJYSI
#define globalNotificationUrl ugdvJNlsBFKMWnQu
#define description rbAynZzKlSnfMpew
#define ClosureWrapper nuYQXBALGmDuENXV
#define SwipeGestureRecognizerClosureWrapper BnNKbbDZaAZekcDn
#define Tools PrMAhRVyXtYdFbDP
#define getOutermostView syCXIGMJKDFOUxYd
#define getViewOfAbsoluteFame frVjBxnuuSbRwFGP
#define originX ZXsJeJOjbrfBDSkC
#define originY iGXPKFjAFHsldtYQ
#define startIndicator UMcleWhHARRwmqkN
#define indicatorContentView ACKAVqdgkWwiPJga
#define topCons datwaGGMKwUwiNmR
#define bottomCons bextHaRyEYbgHwAu
#define leadCons emxDOWkKmoqrGLTz
#define trailCons bKBzJgFSpfxzpiQM
#define indicatorView vURpcxCdXwSEsyzh
#define centerXCons HtViNNVWeciHYtrU
#define centerYCons JFxjKPwYPTugPbDC
#define cancelBtn pPSWLsBDPOoEEWAt
#define topCons1 uqSJKGXTybYeekrQ
#define bottomCons1 BzvvECYSJyjSzIND
#define leadCons1 LDgZJGqWeaQTVHDr
#define trailCons1 lKOZWhvyPiMxMCqX
#define stopIndicator vMqOFTtyAiElrrUP
#define resizeImageLimited TUWNscmLvcDEvDyS
#define httpConnect RBDTJXLysdCgiQuR
#define downloadImage wYrvPNjAHwkSyFZD
#define downloadJasonDataAsDictionary RImMTNYzshjpHXgh
#define downloadJasonDataAsArray UjNPiRaMUiPWEtTl
#define backToViewController cubSMvBLstMbehdZ
#define ViewController yiEjPnQfbpldyfdp
#define StyledPageControl tckycOLCfBOGOYzZ
#define resultArray jKgqIuaGIhsJEMJT
#define adsArray jbzyriEIzGPYPYpS
#define adScrollView myfHpkGcVgMujSQD
#define pageControl SjRNlurxfkqIhjAE
#define pageControlIsChangingPage vFUkvbTnKaoSOIgW
#define forward GneHxmwWWZDfkxiA
#define topBarAdUrl JvGmJxocvLLHoizG
#define ASIHTTPRequest JAGHQSGfDDsGzjoP
#define _currentPage tCwqZkxZQezAaCDX
#define tableView GCoydrDgfiiPEOan
#define httpRequests LwtqCpgyUNEoSOFD
#define homeButton wMcXPIktyNmDbZkV
#define featureButton mSaCdClIKWjUTBiB
#define containerView fqmJOtNgTqCHlqYv
#define mContainerVCArr fONJnocRkbjOsome
#define mTabBarButtonArr LiBSjuObzfZEQWWQ
#define tabBarTitles txzusJNLbcfZzhJL
#define tabBarImages vEOXyJrNDUDuRbFZ
#define tabBarColor XybbvyundpHXhcuY
#define tabBarTitleColor gSavXqaAOnIGhCXh
#define dataQuery1 MNerENWoPwPvdGoy
#define avObject1 PjiASkhmmlECphzF
#define adController cuvIuedyGripiOJu
#define language KuNrbSlhvfohssWH
#define dataQuery2 mOhMLOUKJAYfMllU
#define avObject2 yoweMlUeEDTLQXUs
#define dest ebkkPuoUjNqaTKTh
#define button01DidTapped kWBZrxoammszeIME
#define storyboard irInOPRApjyBlhvi
#define dVC HRGqvdVZGNiPYPgY
#define setBottomTab EwdxodHorqvFeSjL
#define btnViewColor woAsBlsPMNBublWR
#define btnBgColor myzYCslWSWMFEzFA
#define btnBorderColor JppcBcleeRpqJTtt
#define btnView01 nucPslwVypbHZWnn
#define button01 lAaWXKjXBcTAIwQK
#define btnSelectRect ItKzWddcZuODquxk
#define contextSelect dgackUMsxfHAyXHE
#define btnSelectColor AUAzBHSNPFluUImg
#define btnSelectImage kaVbEOHjHPqgozqd
#define btnNormalRect ZwvgHEJcIBbWUJQL
#define contextNormal FpfoulgFnASuEKTC
#define btnNormalColor sCPxdyRpOECwMHsE
#define btnNormalImage WErTNhHKkvXeJvwh
#define refresh dqdfdOWtbbhXdSbl
#define loadClientInfo kQtkuKpaNZgBiIWg
#define requests piLWnkInNPAdydqb
#define request bhmAuSMyfMPMSOxZ
#define responseData lyXjGckmSwubMfwS
#define ret OJKnvNsoBkpTKHVR
#define _result UIgwDMnwATimRwRC
#define loadTopbarAd WWjahgpNTZAjJeXK
#define loadAds gtRULrikyLjhyyKR
#define loadMoreData pUMAxIATVFEFSPKn
#define loadData YocXNPaPPvjKlmEN
#define urlStr YfphyPHlEKYnkHPl
#define info csUsbYTrFypVXvwM
#define MyIdentifier yJYrcwOAIwAXqkRU
#define detailViewController ARdqTgQvpkddBLiz
#define tOWebViewController DQKmjiEbyphpoShF
#define bgColor TcxKkuXyZsOhlBMK
#define customView qrUMwfwfQjDhbQII
#define headerLabel sWywVnsJWEnraxKG
#define Btn gYBLolUAEgTiXcbb
#define gotoUrl aoYBVavWNCwIQnEo
#define dd QoPzDgYagbMSEgTg
#define buildHeader LEmDNFUamevHvUJK
#define flash QlXQQvTNLbLZSoAh
#define setupPage etlqtmNFMjLFMJeG
#define pageWidth vQEbpJKpnrNzWdEy
#define page rsKoqDhDQtlJlNpe
#define changePage UfGZiDpKiMYkEOGA
#define pageControlPageDidChange bWxHXmvCCxwaEbcE
#define uploadIDFAData KkmstziBopjKCSxJ
#define _client_id YBrHaGxzJprDhwcY
#define rawData zgfcSnwcyIVkDWHn
#define checkServerStatus eTHokYKfLIQILAmm
#define isNeedUpdate wRDcDAHdcOuaWGlo
#define description EPqIKujekYdDfUPh
#define alertCtrl WstHDvjKDqaFtvkp
#define cancelAction JlEXlpjBdcKOQRuR
#define confirmAction oYiXebnSjQuliHiF
#define ADWKWebViewController oXYqeFiJDNBIUoNF
#define webViewURL kfobhXjKRRZrTlNy
#define layoutBottomBarHeight MWUDohpOZZHiUXDX
#define hostReachability SiXCWUZkbEQhMyLK
#define internetReachability CvlutySpjsZxmpgh
#define isLoadFinish lrrtKcZrCTnMcrBS
#define isLandscape iwoELuzUPnASNNQL
#define wkwebView PFEsZQyzqrCLtfoD
#define noNetView mIFswiTDjnvVVffc
#define alertView xujGFCPZvHGYRIkV
#define bottomBarView iDLTEMijfYFyPOuf
#define activityIndicatorView aYNJFWzGkJxahMkY
#define bottomBarHeightConstraint qEFOnugIwFJuZoMt
#define openSomeTheAppWithWKWebView zsCbBXXggzjHARWz
#define openOtherAppWithWKWebView wwcLLYXuMwprlglp
#define whitelist YLJpEtPZEnmSXbBh
#define rulesString YvlSMcdlptDWZyPX
#define alertController SfMVLTegbVinrxUM
#define ADReachability ParCYhTftKsiaODq
#define xReachabilityChangedNotification mvEtXOWoMKBtFAGn
#define reachabilityWithHostName sFAsxCOAorBnuDpP
#define reachabilityWithAddress JfGEgFjVtPWeSOUx
#define reachabilityForInternetConnection yDfzQfvmkhosPeHo
#define startNotifier onlTpcBPHZqwomtt
#define stopNotifier QfracTGpFmiFCCnJ
#define currentReachabilityStatus zaXMyQDcpWIWREIM
#define connectionRequired cAynaHAhIYmclGNg
#define PrintReachabilityFlags wOTLfyBQONCDwKQW
#define ReachabilityCallback AXnNJJHJLGhUdyvH
#define noteObject vBxlPzvbqhiaLNWY
#define _reachabilityRef wUuCmrSQiijarcnG
#define returnValue ZyVlhdHmFsJEVFSW
#define reachability EvmdsbfUtXgqzsiq
#define zeroAddress RkSmWpNhUxfQdZFh
#define networkStatusForFlags gaYxtahOnSYFvGmX
#define BaseViewController QNneRaxpyEBurXPc
#define BaseTableViewController whrJiPbPICwTsdjI
#define SideMenuViewController XUxieEAkIEPJZiPM
#define HomeViewController OfsgtgiTpkNSaVJH
#define HomeTableViewCell qRMSDrNQKamXBpkW
#define DataListViewController FftBjUOnFWwFloBa
#define BookmarkViewController iOHwMWAoImaLhUFs
#define MoreViewController ybsXLfQumtwymfaz
#define MoreAppCell dBuDYCDWJoEcyFxf
#define DetailViewController OQZracuEXzbvWved
#define TOActivityChrome XdemOkfewFvegDgM
#define TOActivitySafari HUOGCVaIxMcloacu
#define TOWebViewController NoLhsVNrrhvwndIj
#define ISObject bIVPeWESBIKYGNDc
#define URLSessionManager uvJPeKbRSWIcTWVn
#define ADViewController tibKnXjPDvFGWxpG
#define ADReachability dVqtUuYQzEnYdJBw
#define trimForURL VXDTtNXXgsHVELql
#define BsTableViewController CesJVLvasUgjuOJf
#define ThemeNavigationController PDdrOfcrfcTWjJLD
#define applyTheme fYxiQoCwuRDkJZqY
#define navigationsetuptest dKzLQNTSmuWIztfF
#define refresh VsULHVtzjtHCoGIb
#define setupUI AmzQpxmgGaUQWBrW
#define createTabButtonWithTitle ekhXURVPzFgqIQxS
#define updateContainerViewControllers AfrfGPhaQOUKeGJc
#define mContainerVCArr VRVwXBhXCnNtzMKV
#define mTabBarButtonArr KvpBBZZhyGQJBelS
#define loadAds GFAFWwCBsgTjzZnT
#define loadPopupAdData LYpIfzHqWioiwuoI
#define loadData gsQJDutMloHRJlQz
#define buildHeader oezlcQXiJBpubZBI
#define isChangeToADViewOK aAxaboSdmGHkVwDz
#define uploadIDFAData szAIiylankXQxggb
#endif
